version: "3.9"
services:
  node_peliculas:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb_peliculas
    depends_on:
      - mariadb_peliculas
  mariadb_peliculas:
    image: mariadb:10.6
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=12345
    volumes:
      - ./queryDb:/docker-entrypoint-initdb.d 